authors_c = {'Agatha Christie',
 'Aldous Huxley',
 'Ambrose Bierce',
 'Andrew Lang',
 'Anthony Trollope',
 'Baronness Orczy',
 'Beatrix Potter',
 'Benjamin Disraeli',
 'Bram Stoker',
 'Bret Harte',
 'Charles Dickens',
 'Charles Kingsley',
 'Charlotte Bronte',
 'Charlotte Mary Yonge',
 'D H Lawrence',
 'Edgar Allan Poe',
 'Edgar Rice Burroughs',
 'Edmund Burke',
 'Edward Phillips Oppenheim',
 'Edward Stratemeyer',
 'Elizabeth Barrett Browning',
 'Emily Bronte',
 'Eugene O_Neill',
 'Ezra Pound',
 'Frank Richard Stockton',
 'G K Chesterton',
 'George Alfred Henty',
 'George Bernard Shaw',
 'George Eliot',
 'Grant Allen',
 'Hamlin Garland',
 'Harold Bindloss',
 'Harriet Elizabeth Beecher Stowe',
 'Hector Hugh Munro',
 'Henry David Thoreau',
 'Henry James',
 'Henry Rider Haggard',
 'Herbert George Wells',
 'Herman Melville',
 'Howard Pyle',
 'Isaac Asimov',
 'Jack London',
 'James Bowker',
 'James Fenimore Cooper',
 'James Joyce',
 'James Matthew Barrie',
 'James Otis',
 'James Russell Lowell',
 'Jane Austen',
 'Jerome Klapka Jerome',
 'John Dryden',
 'John Galsworthy',
 'John Keats',
 'Joseph Conrad',
 'Leigh Hunt',
 'Lewis Carroll',
 'Lord Byron',
 'Lord Tennyson',
 'Louisa May Alcott',
 'Lucy Maud Montgomery',
 'Lyman Frank Baum',
 'Mark Twain',
 'Mary Shelley',
 'Mary Stewart Daggett',
 'Nathaniel Hawthorne',
 'O Henry',
 'Oscar Wilde',
 'P B Shelley',
 'P G Wodehouse',
 'Percival Lowell',
 'Philip Kindred Dick',
 'R M Ballantyne',
 'Rafael Sabatini',
 'Ralph Waldo Emerson',
 'Robert Browning',
 'Robert Frost',
 'Robert Louis Stevenson',
 'Robert Southey',
 'Rudyard Kipling',
 'Samuel Taylor Coleridge',
 'Sinclair Lewis',
 'Sir Arthur Conan Doyle',
 'Sir Walter Scott',
 'Sir William Schwenck Gilbert',
 'Stephen Leacock',
 'T S Eliot',
 'Thomas Hardy',
 'Thornton Waldo Burgess',
 'Virginia Woolf',
 'Walt Whitman',
 'Walter de la Mare',
 'Washington Irving',
 'Wilkie Collins',
 'William Blake',
 'William Butler Yeats',
 'William Dean Howells',
 'William Henry Hudson',
 'William J Long',
 'William Makepeace Thackeray',
 'William Somerset Maugham',
 'William Wordsworth',
 'William Wymark Jacobs',
 'Zane Grey'}

non_fiction = {"Andrew Lang's Introduction to The Compleat Angler",
              "Letters on Literature",
              "Letters to Dead Authors",
              "Shakespeare, Bacon and the Great Unknown",
              "Sir Walter Scott and the Border Minstrelsy",
               "Autobiography of Anthony Trollope",
               "Autobiography of Benjamin Franklin, Version 1",
               "Autobiography of Benjamin Franklin, Version 2",
               "Autobiography of Benjamin Franklin, Version 3",
               "Autobiography of Benjamin Franklin, Version 4",
               "Biographies of Working Men",
               "Essays, First Series",
               "Essays, Second Series",
               "Essays",
               "Essays of Robert Louis Stevenson",
               "Letters of Robert Louis Stevenson, Volume 1",
               "Letters of Robert Louis Stevenson, Volume 2",
               "Colloquies on Society",
               "Shakespeare, Ben Jonson, Beaumont and Fletcher",
               "Hints towards the formation of a more comprehensive theory of life",
               "Specimens of the Table Talk of S.T.Coleridge",
               "Personal Narrative of a Pilgrimage to Al-Madinah & Meccah, Volume 1",
               "Personal Narrative of a Pilgrimage to Al-Madinah & Meccah, Volume 2",
               "The Dawn of Canadian History - A Chronicle of Aboriginal Canada",
               "The Unsolved Riddle of Social Justice",
               "The Life of Horatio Lord Nelson"
              }